# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ojitha @ GitHub
author:
  name: Ojitha Kumanayaka
  email: "ojithak@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  I am Ojitha Kumanayaka, the certified Java software engineer and AWS certified associate developer from Australia.
baseurl: / # the subpath of your site, e.g. /blog
url: "https://ojitha.github.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-12622200-2
timezone: Australia/Sydney
show_excerpts: true

header_pages:
  - about.md
  - projects.md
  - blog.md
  - notes.md
  - search.html

# theme: minima
remote_theme: jekyll/minima
minima:
  skin: classic
  social_links:
    twitter: ojitha
    github: ojitha
    linkedin: ojitha
    stackoverflow: "546792"

copyright: "Copyright © 2020 Ojitha Kumanayaka"

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->
paginate: 5

algolia:
  application_id: 247I9HI0FJ
  index_name: ojitha_github_io
  search_only_api_key: c0e739fba2a9fa6f1de62c04507daf1d
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-algolia
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
