version: '3.8'
services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      # - .:/app:delegated  # delegated improves performance on macOS
      - .:/app # for Ubuntu
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  bundle_cache: